### ISSUE TITLE
Provide an App please

### ISSUE THREAD

**Issue by Pragalbha-Patil** [jai-k-gohil/Airlines_app#1]
Hey, really interested in your project, can you provide a release? an apk preferably if possible?

**Comment by jai-k-gohil** [comment]
From the console
1. For apk (Android) you need to run the command : flutter build apk --release
2. For ipa (iOS) you need to run the command : flutter build ios --release
P.S. --release is optional as it is by default if you need debug build, just replace --release with --debug
